services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sonya_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sonya_lab_pgdata:/var/lib/postgresql/data

volumes:
  sonya_lab_pgdata:
