AIRPORTS = [
    {"code": "ICN", "city": "서울/인천", "name": "인천국제공항", "country": "대한민국", "region": "other"},
    {"code": "GMP", "city": "서울", "name": "김포국제공항", "country": "대한민국", "region": "other"},
    {"code": "PUS", "city": "부산", "name": "김해국제공항", "country": "대한민국", "region": "other"},
    {"code": "CJU", "city": "제주", "name": "제주국제공항", "country": "대한민국", "region": "other"},
    {"code": "NRT", "city": "도쿄", "name": "나리타 국제공항", "country": "일본", "region": "other"},
    {"code": "HND", "city": "도쿄", "name": "하네다 공항", "country": "일본", "region": "other"},
    {"code": "KIX", "city": "오사카", "name": "간사이 국제공항", "country": "일본", "region": "other"},
    {"code": "PEK", "city": "베이징", "name": "베이징 수도 국제공항", "country": "중국", "region": "other"},
    {"code": "PVG", "city": "상하이", "name": "푸둥 국제공항", "country": "중국", "region": "other"},
    {"code": "HKG", "city": "홍콩", "name": "홍콩 국제공항", "country": "홍콩", "region": "other"},
    {"code": "TPE", "city": "타이베이", "name": "타오위안 국제공항", "country": "대만", "region": "other"},
    {"code": "SIN", "city": "싱가포르", "name": "창이 공항", "country": "싱가포르", "region": "other"},
    {"code": "BKK", "city": "방콕", "name": "수완나품 공항", "country": "태국", "region": "other"},
    {"code": "SGN", "city": "호찌민", "name": "떤선녓 국제공항", "country": "베트남", "region": "other"},
    {"code": "HAN", "city": "하노이", "name": "노이바이 국제공항", "country": "베트남", "region": "other"},
    {"code": "DPS", "city": "발리", "name": "응우라라이 국제공항", "country": "인도네시아", "region": "other"},
    {"code": "KUL", "city": "쿠알라룸푸르", "name": "쿠알라룸푸르 국제공항", "country": "말레이시아", "region": "other"},
    {"code": "DEL", "city": "델리", "name": "인디라 간디 국제공항", "country": "인도", "region": "other"},
    {"code": "DXB", "city": "두바이", "name": "두바이 국제공항", "country": "아랍에미리트", "region": "other"},
    {"code": "DOH", "city": "도하", "name": "하마드 국제공항", "country": "카타르", "region": "other"},
    {"code": "LHR", "city": "런던", "name": "히드로 공항", "country": "영국", "region": "europe"},
    {"code": "LGW", "city": "런던", "name": "개트윅 공항", "country": "영국", "region": "europe"},
    {"code": "CDG", "city": "파리", "name": "샤를 드골 공항", "country": "프랑스", "region": "europe"},
    {"code": "ORY", "city": "파리", "name": "오를리 공항", "country": "프랑스", "region": "europe"},
    {"code": "FRA", "city": "프랑크푸르트", "name": "프랑크푸르트 공항", "country": "독일", "region": "europe"},
    {"code": "MUC", "city": "뮌헨", "name": "뮌헨 공항", "country": "독일", "region": "europe"},
    {"code": "AMS", "city": "암스테르담", "name": "스키폴 공항", "country": "네덜란드", "region": "europe"},
    {"code": "FCO", "city": "로마", "name": "피우미치노 공항", "country": "이탈리아", "region": "europe"},
    {"code": "MXP", "city": "밀라노", "name": "말펜사 공항", "country": "이탈리아", "region": "europe"},
    {"code": "MAD", "city": "마드리드", "name": "바라하스 공항", "country": "스페인", "region": "europe"},
    {"code": "BCN", "city": "바르셀로나", "name": "엘프라트 공항", "country": "스페인", "region": "europe"},
    {"code": "LIS", "city": "리스본", "name": "움베르투 델가두 공항", "country": "포르투갈", "region": "europe"},
    {"code": "ZRH", "city": "취리히", "name": "취리히 공항", "country": "스위스", "region": "europe"},
    {"code": "VIE", "city": "빈", "name": "빈 국제공항", "country": "오스트리아", "region": "europe"},
    {"code": "PRG", "city": "프라하", "name": "바츨라프 하벨 공항", "country": "체코", "region": "europe"},
    {"code": "WAW", "city": "바르샤바", "name": "쇼팽 공항", "country": "폴란드", "region": "europe"},
    {"code": "HEL", "city": "헬싱키", "name": "헬싱키 공항", "country": "핀란드", "region": "europe"},
    {"code": "CPH", "city": "코펜하겐", "name": "코펜하겐 공항", "country": "덴마크", "region": "europe"},
    {"code": "ARN", "city": "스톡홀름", "name": "알란다 공항", "country": "스웨덴", "region": "europe"},
    {"code": "ATH", "city": "아테네", "name": "아테네 국제공항", "country": "그리스", "region": "europe"},
    {"code": "IST", "city": "이스탄불", "name": "이스탄불 공항", "country": "튀르키예", "region": "europe"},
    {"code": "JFK", "city": "뉴욕", "name": "존 F. 케네디 국제공항", "country": "미국", "region": "united_states"},
    {"code": "EWR", "city": "뉴욕/뉴어크", "name": "뉴어크 리버티 국제공항", "country": "미국", "region": "united_states"},
    {"code": "LAX", "city": "로스앤젤레스", "name": "로스앤젤레스 국제공항", "country": "미국", "region": "united_states"},
    {"code": "SFO", "city": "샌프란시스코", "name": "샌프란시스코 국제공항", "country": "미국", "region": "united_states"},
    {"code": "SEA", "city": "시애틀", "name": "시애틀 터코마 국제공항", "country": "미국", "region": "united_states"},
    {"code": "ORD", "city": "시카고", "name": "오헤어 국제공항", "country": "미국", "region": "united_states"},
    {"code": "BOS", "city": "보스턴", "name": "로건 국제공항", "country": "미국", "region": "united_states"},
    {"code": "IAD", "city": "워싱턴 D.C.", "name": "덜레스 국제공항", "country": "미국", "region": "united_states"},
    {"code": "DFW", "city": "댈러스", "name": "댈러스 포트워스 국제공항", "country": "미국", "region": "united_states"},
    {"code": "ATL", "city": "애틀랜타", "name": "하츠필드 잭슨 국제공항", "country": "미국", "region": "united_states"},
    {"code": "LAS", "city": "라스베이거스", "name": "해리 리드 국제공항", "country": "미국", "region": "united_states"},
    {"code": "HNL", "city": "호놀룰루", "name": "대니얼 K. 이노우에 국제공항", "country": "미국", "region": "united_states"},
    {"code": "YYZ", "city": "토론토", "name": "피어슨 국제공항", "country": "캐나다", "region": "canada"},
    {"code": "YVR", "city": "밴쿠버", "name": "밴쿠버 국제공항", "country": "캐나다", "region": "canada"},
    {"code": "YUL", "city": "몬트리올", "name": "트뤼도 국제공항", "country": "캐나다", "region": "canada"},
    {"code": "YYC", "city": "캘거리", "name": "캘거리 국제공항", "country": "캐나다", "region": "canada"},
    {"code": "SYD", "city": "시드니", "name": "킹스포드 스미스 공항", "country": "호주", "region": "australia"},
    {"code": "MEL", "city": "멜버른", "name": "멜버른 공항", "country": "호주", "region": "australia"},
    {"code": "BNE", "city": "브리즈번", "name": "브리즈번 공항", "country": "호주", "region": "australia"},
    {"code": "PER", "city": "퍼스", "name": "퍼스 공항", "country": "호주", "region": "australia"},
    {"code": "AKL", "city": "오클랜드", "name": "오클랜드 공항", "country": "뉴질랜드", "region": "other"},
]


def search_airports(query: str = "") -> list[dict[str, str]]:
    needle = query.strip().casefold()
    if not needle:
        return AIRPORTS
    return [airport for airport in AIRPORTS if needle in " ".join(airport.values()).casefold()]
