"""initial persistent service schema

Revision ID: 308c4f7340fc
Revises: 
Create Date: 2026-07-12 14:30:25.993215
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '308c4f7340fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_watches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('destination_region', sa.String(length=32), nullable=False),
    sa.Column('departure_date_from', sa.Date(), nullable=False),
    sa.Column('departure_date_to', sa.Date(), nullable=False),
    sa.Column('trip_nights_min', sa.Integer(), nullable=False),
    sa.Column('trip_nights_max', sa.Integer(), nullable=False),
    sa.Column('drop_threshold_pct', sa.Float(), nullable=False),
    sa.Column('direct_only', sa.Boolean(), nullable=False),
    sa.Column('baggage_required', sa.Boolean(), nullable=False),
    sa.Column('collection_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('collection_enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_watch_due', 'flight_watches', ['collection_enabled', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_flight_watches_user_id'), 'flight_watches', ['user_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index(op.f('ix_notification_events_event_type'), 'notification_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_events_user_id'), 'notification_events', ['user_id'], unique=False)
    op.create_table('paper_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_collections_user_id'), 'paper_collections', ['user_id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors_json', sa.JSON(), nullable=False),
    sa.Column('journal', sa.String(length=500), nullable=False),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('open_access', sa.Boolean(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('metadata_sources_json', sa.JSON(), nullable=False),
    sa.Column('ranking_components_json', sa.JSON(), nullable=False),
    sa.Column('raw_data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('saved_paper_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('collection_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('collection_enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_paper_search_due', 'saved_paper_searches', ['collection_enabled', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_saved_paper_searches_user_id'), 'saved_paper_searches', ['user_id'], unique=False)
    op.create_table('scheduler_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_runs_job_type'), 'scheduler_runs', ['job_type'], unique=False)
    op.create_index(op.f('ix_scheduler_runs_target_id'), 'scheduler_runs', ['target_id'], unique=False)
    op.create_table('flight_price_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watch_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_offer_id', sa.String(length=255), nullable=False),
    sa.Column('airline', sa.String(length=160), nullable=False),
    sa.Column('flight_numbers_json', sa.JSON(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('stop_places_json', sa.JSON(), nullable=False),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('baggage_included', sa.Boolean(), nullable=False),
    sa.Column('baggage_summary', sa.Text(), nullable=False),
    sa.Column('total_price_krw', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('booking_url', sa.Text(), nullable=False),
    sa.Column('seller_name', sa.String(length=160), nullable=False),
    sa.Column('seller_domain', sa.String(length=255), nullable=False),
    sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taxes_included', sa.Boolean(), nullable=True),
    sa.Column('fees_included', sa.Boolean(), nullable=True),
    sa.Column('refundable', sa.Boolean(), nullable=True),
    sa.Column('changeable', sa.Boolean(), nullable=True),
    sa.Column('fare_type', sa.String(length=100), nullable=False),
    sa.Column('fare_conditions_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['flight_watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_id', 'provider', 'external_offer_id', 'observed_at', name='uq_flight_offer_observation')
    )
    op.create_index(op.f('ix_flight_price_observations_observed_at'), 'flight_price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_flight_price_observations_watch_id'), 'flight_price_observations', ['watch_id'], unique=False)
    op.create_table('paper_library_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('reading_status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['paper_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_user_paper_library')
    )
    op.create_index(op.f('ix_paper_library_items_paper_id'), 'paper_library_items', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_library_items_user_id'), 'paper_library_items', ['user_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_library_items_user_id'), table_name='paper_library_items')
    op.drop_index(op.f('ix_paper_library_items_paper_id'), table_name='paper_library_items')
    op.drop_table('paper_library_items')
    op.drop_index(op.f('ix_flight_price_observations_watch_id'), table_name='flight_price_observations')
    op.drop_index(op.f('ix_flight_price_observations_observed_at'), table_name='flight_price_observations')
    op.drop_table('flight_price_observations')
    op.drop_index(op.f('ix_scheduler_runs_target_id'), table_name='scheduler_runs')
    op.drop_index(op.f('ix_scheduler_runs_job_type'), table_name='scheduler_runs')
    op.drop_table('scheduler_runs')
    op.drop_index(op.f('ix_saved_paper_searches_user_id'), table_name='saved_paper_searches')
    op.drop_index('ix_saved_paper_search_due', table_name='saved_paper_searches')
    op.drop_table('saved_paper_searches')
    op.drop_table('papers')
    op.drop_index(op.f('ix_paper_collections_user_id'), table_name='paper_collections')
    op.drop_table('paper_collections')
    op.drop_index(op.f('ix_notification_events_user_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_event_type'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_flight_watches_user_id'), table_name='flight_watches')
    op.drop_index('ix_flight_watch_due', table_name='flight_watches')
    op.drop_table('flight_watches')
    # ### end Alembic commands ###
