<script setup>
import { computed, onMounted, reactive, ref } from 'vue'

const apiBase = import.meta.env.VITE_API_BASE_URL || ''
const tab = ref('flights'), loading = ref(false), error = ref(''), notice = ref('')
const watches = ref([]), airports = ref([]), selectedId = ref(''), trend = ref([])
const papers = ref([]), library = ref([]), runs = ref([]), settings = ref(null), provider = ref('')
const savedSearches = ref([]), paperSchedule = ref('manual')
const collections = ref([]), selectedLibraryId = ref(''), libraryEdit = reactive({note:'',tags:'',collection_id:null,priority:0})
const summaries = reactive({}), summaryLoading = ref('')
const today = new Date(); const dateAfter = d => { const x=new Date(today); x.setDate(x.getDate()+d); return x.toISOString().slice(0,10) }
const watchForm = reactive({origin:'ICN',destination:'LHR',destination_region:'europe',departure_date_from:dateAfter(60),departure_date_to:dateAfter(74),trip_nights_min:5,trip_nights_max:10,drop_threshold_pct:25,direct_only:true,baggage_required:true,collection_interval_minutes:360,collection_enabled:true,timezone:'Asia/Seoul'})
const priceForm = reactive({total_price_krw:1100000,provider:'manual',airline:'',direct:true,baggage_included:true,currency:'KRW',booking_url:'',seller_name:'',confidence:'low'})
const paperForm = reactive({query:'',field:'',author:'',journal:'',published_within_years:2,open_access_only:false,minimum_citations:0,sort_by:'relevance',limit:10,notify_new_results:false})
const summaryMode = ref('key')
const selected = computed(()=>watches.value.find(w=>w.id===selectedId.value))
const regionNames={europe:'유럽',australia:'호주',united_states:'미국',canada:'캐나다',other:'기타'}
const intervals=[{v:60,n:'1시간'},{v:180,n:'3시간'},{v:360,n:'6시간'},{v:720,n:'12시간'},{v:1440,n:'하루 1회'}]
const won=v=>v==null?'데이터 없음':`${Number(v).toLocaleString('ko-KR')}원`
const time=v=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—'
const intervalName=v=>intervals.find(x=>x.v===v)?.n||`${v}분`
const trendPoints=computed(()=>{if(trend.value.length<2)return'';const p=trend.value.map(x=>x.total_price_krw),min=Math.min(...p),max=Math.max(...p),range=max-min||1;return trend.value.map((x,i)=>`${4+i/(trend.value.length-1)*92},${88-(x.total_price_krw-min)/range*76}`).join(' ')})

async function request(path,options={}){error.value='';const response=await fetch(`${apiBase}${path}`,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`요청 실패 (HTTP ${response.status})`)}return response.json()}
async function loadWatches(){try{watches.value=await request('/api/flights/watches');if(!selectedId.value&&watches.value.length)selectedId.value=watches.value[0].id}catch(e){error.value=e.message}}
async function loadAll(){await Promise.allSettled([loadWatches(),request('/api/flights/airports').then(v=>airports.value=v),request('/api/papers/library').then(v=>library.value=v),request('/api/papers/collections').then(v=>collections.value=v),request('/api/papers/saved-searches').then(v=>savedSearches.value=v),request('/api/scheduler/runs').then(v=>runs.value=v),request('/api/system/settings').then(v=>settings.value=v)])}
function syncRegion(){const a=airports.value.find(x=>x.code===watchForm.destination.toUpperCase());if(a)watchForm.destination_region=a.region}
async function createWatch(){loading.value=true;try{const w=await request('/api/flights/watches',{method:'POST',body:JSON.stringify(watchForm)});notice.value=`${w.origin} → ${w.destination} 감시를 저장했습니다.`;selectedId.value=w.id;await loadWatches()}catch(e){error.value=e.message}finally{loading.value=false}}
async function toggleWatch(w){try{await request(`/api/flights/watches/${w.id}`,{method:'PATCH',body:JSON.stringify({collection_enabled:!w.collection_enabled})});await loadWatches()}catch(e){error.value=e.message}}
async function runWatch(w){loading.value=true;try{const run=await request(`/api/scheduler/flights/${w.id}/run`,{method:'POST'});notice.value=run?.status==='success'?'항공권 검색을 완료했습니다.':`검색 상태: ${run?.status}`;await loadAll()}catch(e){error.value=e.message}finally{loading.value=false}}
async function addPrice(){if(!selected.value)return;loading.value=true;try{await request(`/api/flights/watches/${selected.value.id}/observations`,{method:'POST',body:JSON.stringify(priceForm)});notice.value='가격을 기록했습니다.';await loadWatches();await showTrend(selected.value)}catch(e){error.value=e.message}finally{loading.value=false}}
async function showTrend(w){selectedId.value=w.id;try{trend.value=await request(`/api/flights/watches/${w.id}/observations?days=365`)}catch(e){error.value=e.message}}
async function searchPapers(){loading.value=true;try{const result=await request('/api/papers/search',{method:'POST',body:JSON.stringify(paperForm)});papers.value=result.results;provider.value=result.provider;notice.value=`실제 논문 ${papers.value.length}건을 찾았습니다.`}catch(e){error.value=e.message}finally{loading.value=false}}
async function savePaperSearch(){try{await request('/api/papers/saved-searches',{method:'POST',body:JSON.stringify({...paperForm,name:paperForm.query,schedule:paperSchedule.value})});savedSearches.value=await request('/api/papers/saved-searches');notice.value='논문 검색 조건을 저장했습니다.'}catch(e){error.value=e.message}}
async function savePaper(paper,status='unread'){try{await request('/api/papers/library',{method:'POST',body:JSON.stringify({paper_id:paper.id,favorite:true,reading_status:status,tags:[]})});notice.value=status==='unread'?'즐겨찾기에 저장했습니다.':'나중에 읽기에 저장했습니다.';library.value=await request('/api/papers/library')}catch(e){error.value=e.message}}
async function updateLibrary(item,changes){try{await request(`/api/papers/library/${item.id}`,{method:'PATCH',body:JSON.stringify(changes)});library.value=await request('/api/papers/library')}catch(e){error.value=e.message}}
function selectLibrary(item){if(!item)return;selectedLibraryId.value=item.id;libraryEdit.note=item.note;libraryEdit.tags=item.tags_json.join(', ');libraryEdit.collection_id=item.collection_id;libraryEdit.priority=item.priority}
async function saveLibraryEdit(){const item=library.value.find(x=>x.id===selectedLibraryId.value);if(!item)return;await updateLibrary(item,{note:libraryEdit.note,tags:libraryEdit.tags.split(',').map(x=>x.trim()).filter(Boolean),collection_id:libraryEdit.collection_id||null,priority:libraryEdit.priority});notice.value='메모와 분류를 저장했습니다.'}
async function createCollection(){const name=window.prompt('새 컬렉션 이름을 입력하세요.');if(!name)return;try{await request('/api/papers/collections',{method:'POST',body:JSON.stringify({name,description:''})});collections.value=await request('/api/papers/collections')}catch(e){error.value=e.message}}
async function deleteLibrary(item){if(!item||!window.confirm(`“${item.paper.title}”을 보관함에서 삭제할까요?`))return;try{await request(`/api/papers/library/${item.id}`,{method:'DELETE'});library.value=await request('/api/papers/library');selectedLibraryId.value=''}catch(e){error.value=e.message}}
async function summarize(paper){summaryLoading.value=paper.external_id;try{summaries[paper.external_id]=await request('/api/papers/summarize',{method:'POST',body:JSON.stringify({title:paper.title,abstract:paper.abstract||'',authors:paper.authors||[],journal:paper.journal,year:paper.year,doi:paper.doi,mode:summaryMode.value})})}catch(e){error.value=e.message}finally{summaryLoading.value=''}}
function safeOpen(url){if(url&&url.startsWith('https://'))window.open(url,'_blank','noopener,noreferrer')}
onMounted(loadAll)
</script>

<template>
<div class="app-shell">
  <aside class="sidebar"><div class="brand"><span class="brand-mark">S</span><div><strong>Sonya Lab</strong><small>독립 탐색 서비스</small></div></div><nav>
    <button v-for="item in [{id:'flights',n:'✈ 항공권'},{id:'papers',n:'⌕ 논문 검색'},{id:'library',n:'★ 내 논문'},{id:'activity',n:'↻ 실행 이력'},{id:'settings',n:'⚙ 설정'}]" :key="item.id" :class="{active:tab===item.id}" @click="tab=item.id">{{item.n}}</button>
  </nav><div class="sidebar-status"><i></i><div><strong>Single-user mode</strong><small>Sonya Lab 독립 실행</small></div></div></aside>
  <main><header class="topbar"><div><p class="eyebrow">SONYA LAB · 5175 / 8002</p><h1>{{({flights:'항공권 감시',papers:'논문 탐색',library:'내 논문 보관함',activity:'수집 실행 이력',settings:'서비스 설정'})[tab]}}</h1></div><div class="system-pill"><span></span>{{settings?.database?.connected?'DB 연결됨':'DB 확인 필요'}}</div></header>
  <div v-if="error" class="toast error">{{error}}</div><div v-else-if="notice" class="toast">{{notice}}</div>

  <template v-if="tab==='flights'">
    <section class="summary-grid"><article><small>활성 감시</small><strong>{{watches.filter(w=>w.collection_enabled).length}}</strong><span>개</span></article><article><small>현재 최저가 있음</small><strong>{{watches.filter(w=>w.current_lowest_price_krw).length}}</strong><span>개</span></article><article><small>공급자</small><strong class="provider-name">{{settings?.flight?.provider||'—'}}</strong><span>{{settings?.mock_mode?'Mock 데이터':'실제 데이터'}}</span></article></section>
    <section class="content-grid"><div class="panel form-panel"><div class="panel-heading"><div><p class="section-label">NEW WATCH</p><h2>새 노선 감시</h2></div></div><form @submit.prevent="createWatch">
      <div class="field-row"><label>출발 공항<input v-model.trim="watchForm.origin" list="airport-list" maxlength="3" required></label><span class="route-arrow">→</span><label>도착 공항<input v-model.trim="watchForm.destination" list="airport-list" maxlength="3" @change="syncRegion" required></label></div><datalist id="airport-list"><option v-for="a in airports" :key="a.code" :value="a.code">{{a.city}} · {{a.name}} · {{a.country}}</option></datalist>
      <div class="field-row"><label>출발일 시작<input v-model="watchForm.departure_date_from" type="date"></label><label>출발일 종료<input v-model="watchForm.departure_date_to" type="date"></label></div><div class="field-row"><label>최소 여행 박수<input v-model.number="watchForm.trip_nights_min" type="number" min="1"></label><label>최대 여행 박수<input v-model.number="watchForm.trip_nights_max" type="number" min="1"></label></div>
      <label title="외부 API 비용과 호출 제한을 보호하기 위해 최소 1시간입니다.">수집 주기<select v-model.number="watchForm.collection_interval_minutes"><option v-for="x in intervals" :key="x.v" :value="x.v">{{x.n}}</option></select></label><label>급락 알림 기준<input v-model.number="watchForm.drop_threshold_pct" type="number" min="1"><em>%</em></label><div class="checks"><label><input v-model="watchForm.direct_only" type="checkbox">직항만</label><label><input v-model="watchForm.baggage_required" type="checkbox">수하물 포함</label></div><button class="primary" :disabled="loading">감시 저장</button>
    </form></div>
    <div class="panel watch-panel"><div class="panel-heading"><div><p class="section-label">CURRENT LOWEST</p><h2>감시 중인 노선</h2></div><span class="count">{{watches.length}}</span></div><div v-if="!watches.length" class="empty"><strong>감시 노선이 없습니다</strong><p>첫 노선을 등록해 주세요.</p></div>
      <article v-for="w in watches" :key="w.id" class="watch-card" :class="{selected:selectedId===w.id}" @click="selectedId=w.id"><div class="route"><b>{{w.origin}}</b><span>✈</span><b>{{w.destination}}</b></div><div class="lowest"><small>현재 구매 가능 최저가</small><strong>{{won(w.current_lowest_price_krw)}}</strong><em v-if="w.drop_pct!=null">기준 대비 {{w.drop_pct}}% 낮음</em></div><div class="watch-meta"><span>{{w.trip_nights_min}}–{{w.trip_nights_max}}박</span><span>{{intervalName(w.collection_interval_minutes)}}</span><span>{{w.provider}}</span><span>{{w.confidence}} · 표본 {{w.sample_count}}</span></div><div class="price-comparison"><span>기준가 {{won(w.baseline_price_krw)}}</span><span>30일 최저 {{won(w.lowest_30d_krw)}}</span></div><div class="watch-times"><span>최근 성공 {{time(w.last_success_at)}}</span><span>다음 검색 {{time(w.next_run_at)}}</span></div><div v-if="w.last_error" class="inline-error">{{w.last_error}}</div><div class="card-actions"><button @click.stop="runWatch(w)">지금 검색</button><button @click.stop="showTrend(w)">트렌드</button><button @click.stop="toggleWatch(w)">{{w.collection_enabled?'일시정지':'다시 시작'}}</button></div></article>
    </div></section>
    <section v-if="selected" class="panel price-panel"><div class="panel-heading"><div><p class="section-label">OFFER DETAIL</p><h2>{{selected.origin}} → {{selected.destination}} 현재 정보</h2></div></div><div v-if="selected.current_offer" class="offer-detail"><div class="offer-price"><small>현재 최저가</small><strong>{{won(selected.current_offer.total_price_krw)}}</strong><span>{{selected.current_offer.seller_name||selected.current_offer.provider}}</span></div><dl><div><dt>항공사</dt><dd>{{selected.current_offer.airline||'정보 없음'}}</dd></div><div><dt>경유</dt><dd>{{selected.current_offer.stops}}회</dd></div><div><dt>수하물</dt><dd>{{selected.current_offer.baggage_summary||'정보 없음'}}</dd></div><div><dt>세금·수수료</dt><dd>{{selected.current_offer.taxes_included===true&&selected.current_offer.fees_included===true?'포함':'확인 필요'}}</dd></div><div><dt>조회 시각</dt><dd>{{time(selected.current_offer.price_verified_at)}}</dd></div><div><dt>유효성</dt><dd>조회 후 가격이 변경될 수 있음</dd></div></dl><button v-if="selected.current_offer.booking_url" class="primary" @click="safeOpen(selected.current_offer.booking_url)">예약 페이지 열기 ↗</button><p v-else class="muted">공급자가 검증된 구매 링크를 제공하지 않았습니다.</p></div><div v-else class="empty compact"><strong>아직 검색된 가격이 없습니다</strong><button class="primary" @click="runWatch(selected)">지금 검색</button></div>
      <form class="price-form" @submit.prevent="addPrice"><label>수동 가격 기록<input v-model.number="priceForm.total_price_krw" type="number"><em>원</em></label><label>항공사<input v-model="priceForm.airline"></label><button class="primary">가격 저장</button></form>
    </section>
    <section v-if="selectedId" class="panel trend-panel"><div class="panel-heading"><div><p class="section-label">COLLECTED PRICES</p><h2>최근 수집 가격 흐름</h2></div><button @click="showTrend(selected)">새로고침</button></div><div v-if="trend.length<2" class="chart-empty"><strong>1년 트렌드를 표시할 데이터가 부족합니다</strong><span>현재 관측 {{trend.length}}개 · 장기 데이터인 것처럼 임의 생성하지 않습니다.</span></div><div v-else><svg class="trend-chart" viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="4" y1="88" x2="96" y2="88"/><polyline :points="trendPoints"/></svg><div class="chart-dates"><span>{{time(trend[0].observed_at)}}</span><span>{{time(trend.at(-1).observed_at)}}</span></div></div></section>
  </template>

  <template v-else-if="tab==='papers'"><section class="panel paper-search"><div><p class="section-label">PAPER PROVIDER</p><h2>실제 논문 검색</h2><p>Crossref 서지정보를 사용하며 각 점수 구성요소와 출처를 표시합니다.</p></div><form @submit.prevent="searchPapers"><input v-model="paperForm.query" placeholder="키워드" required><input v-model="paperForm.author" placeholder="저자"><select v-model="paperForm.sort_by"><option value="relevance">관련도</option><option value="newest">최신순</option><option value="citations">인용순</option></select><button class="primary">검색</button></form></section><div v-if="provider" class="provider-note"><strong>{{provider}} 실제 데이터</strong></div><section class="paper-list"><article v-for="p in papers" :key="p.external_id" class="paper-card"><div class="score">{{Math.round(p.score*100)}}</div><div><small>{{p.journal}} · {{p.year||'연도 미상'}} · 인용 {{p.citation_count}}회</small><h3><a :href="p.url" target="_blank" rel="noopener noreferrer">{{p.title}} ↗</a></h3><p class="authors">{{p.authors?.slice(0,5).join(', ')}}</p><p>{{p.abstract||'제공된 초록이 없습니다.'}}</p><div class="rank-breakdown"><span v-for="(v,k) in p.ranking_components" :key="k" v-show="typeof v==='number'">{{k}} {{Math.round(v*100)}}</span></div><div class="card-actions"><button @click="savePaper(p)">★ 즐겨찾기</button><button @click="savePaper(p,'reading')">나중에 읽기</button><select v-model="summaryMode"><option value="key">핵심 요약</option><option value="story">이야기형</option><option value="engineer">엔지니어</option><option value="practical">실무 적용</option><option value="critical">비판적 검토</option></select><button @click="summarize(p)">{{summaryLoading===p.external_id?'요약 중…':'한국어 요약'}}</button></div><div v-if="summaries[p.external_id]" class="korean-summary"><span class="summary-scope">{{summaries[p.external_id].source_scope==='abstract_only'?'초록 기반 요약':'메타데이터 기반 안내'}}</span><h4>{{summaries[p.external_id].korean_title}}</h4><p>{{summaries[p.external_id].overview}}</p><strong>주요 내용</strong><ul><li v-for="x in summaries[p.external_id].key_points" :key="x">{{x}}</li></ul><strong>한계</strong><p>{{summaries[p.external_id].limitations}}</p><strong>실무 적용</strong><p>{{summaries[p.external_id].practical_implications}}</p></div></div></article><div v-if="!papers.length" class="panel empty"><strong>검색 결과가 여기에 표시됩니다</strong></div></section></template>

  <template v-else-if="tab==='library'"><section class="paper-list"><article v-for="item in library" :key="item.id" class="paper-card"><div class="score">{{item.priority||'★'}}</div><div><small>{{item.reading_status}} · {{item.tags_json.join(', ')||'태그 없음'}}</small><h3><a :href="item.paper.url" target="_blank" rel="noopener noreferrer">{{item.paper.title}} ↗</a></h3><p>{{item.note||'개인 메모가 없습니다.'}}</p><div class="card-actions"><button @click="updateLibrary(item,{favorite:!item.favorite})">{{item.favorite?'★ 즐겨찾기 해제':'☆ 즐겨찾기'}}</button><select :value="item.reading_status" @change="updateLibrary(item,{reading_status:$event.target.value})"><option value="unread">읽지 않음</option><option value="reading">읽는 중</option><option value="read">읽음</option><option value="archived">보관</option></select></div></div></article><div v-if="!library.length" class="panel empty"><strong>저장한 논문이 없습니다</strong></div></section></template>

  <template v-else-if="tab==='activity'"><section class="panel table-panel"><table><thead><tr><th>작업</th><th>실행 방식</th><th>상태</th><th>공급자</th><th>처리</th><th>시작</th><th>오류</th></tr></thead><tbody><tr v-for="r in runs" :key="r.id"><td>{{r.job_type}}</td><td>{{r.trigger_type}}</td><td><span class="status" :class="r.status">{{r.status}}</span></td><td>{{r.provider}}</td><td>{{r.processed_count}}</td><td>{{time(r.started_at)}}</td><td>{{r.error_message||'—'}}</td></tr></tbody></table><div v-if="!runs.length" class="empty compact">실행 이력이 없습니다.</div></section></template>

  <template v-else><section v-if="settings" class="settings-grid"><article class="panel"><h2>공통</h2><dl><div><dt>실행 모드</dt><dd>{{settings.mode}}</dd></div><div><dt>시간대</dt><dd>{{settings.timezone}}</dd></div><div><dt>기본 통화</dt><dd>{{settings.currency}}</dd></div><div><dt>DB</dt><dd>{{settings.database.connected?'연결 성공':'연결 실패'}}</dd></div><div><dt>Backend</dt><dd>8002 · {{settings.backend.status}}</dd></div><div><dt>Frontend</dt><dd>5175 · v{{settings.frontend.version}}</dd></div></dl></article><article class="panel"><h2>항공권</h2><dl><div><dt>Provider</dt><dd>{{settings.flight.provider}}</dd></div><div><dt>데이터</dt><dd>{{settings.mock_mode?'Mock':'실제'}}</dd></div><div><dt>연결</dt><dd>{{settings.flight.connected?'성공':'실패'}}</dd></div><div><dt>최소 주기</dt><dd>{{settings.flight.minimum_interval_minutes}}분</dd></div><div><dt>API 키</dt><dd>{{settings.flight.api_key_configured?'설정됨':'미설정'}}</dd></div></dl></article><article class="panel"><h2>논문</h2><dl><div><dt>Provider</dt><dd>{{settings.paper.provider}}</dd></div><div><dt>연결</dt><dd>{{settings.paper.connected?'성공':'실패'}}</dd></div><div><dt>AI 요약</dt><dd>{{settings.paper.ai_summary_available?'사용 가능':'키 미설정'}}</dd></div><div><dt>기본 요약</dt><dd>{{settings.paper.default_summary_mode}}</dd></div></dl></article></section></template>
  <section v-if="tab==='papers'" class="panel saved-search-panel"><div><p class="section-label">SAVED SEARCH</p><h2>논문 검색 조건 저장</h2><p>현재 입력한 키워드를 독립 scheduler가 다시 검색합니다.</p></div><select v-model="paperSchedule"><option value="manual">수동 검색만</option><option value="daily">하루 1회</option><option value="every_3_days">3일에 1회</option><option value="weekly">주 1회</option></select><button class="primary" @click="savePaperSearch">현재 검색 조건 저장</button><div class="saved-searches"><span v-for="s in savedSearches" :key="s.id">{{s.name}} · {{s.collection_enabled?(s.collection_interval_minutes/1440)+'일마다':'수동'}}</span></div></section>
  <section v-if="tab==='library'" class="panel library-manager"><div><p class="section-label">LIBRARY ORGANIZER</p><h2>태그·메모·컬렉션 관리</h2></div><select v-model="selectedLibraryId" @change="selectLibrary(library.find(x=>x.id===selectedLibraryId))"><option value="">논문 선택</option><option v-for="item in library" :key="item.id" :value="item.id">{{item.paper.title}}</option></select><textarea v-model="libraryEdit.note" placeholder="개인 메모"></textarea><input v-model="libraryEdit.tags" placeholder="태그를 쉼표로 구분"><select v-model="libraryEdit.collection_id"><option :value="null">컬렉션 없음</option><option v-for="c in collections" :key="c.id" :value="c.id">{{c.name}}</option></select><input v-model.number="libraryEdit.priority" type="number" min="0" max="5" title="중요도 0~5"><div class="card-actions"><button @click="createCollection">컬렉션 추가</button><button class="primary" @click="saveLibraryEdit">저장</button><button v-if="selectedLibraryId" @click="deleteLibrary(library.find(x=>x.id===selectedLibraryId))">보관함에서 삭제</button></div></section>
  </main>
</div>
</template>
